language: python
python:
- '3.7'
install:
- make install-dev
script:
- make coverage
deploy:
  provider: pypi
  user: ocrawford555
  on:
    branch: pypi
  password:
    secure: AzMDypnvsgB7pQ7acD+wT+B/U/fhnQWC+kBkzhMFmtgkD7+6Gc+TmbQOnxLy1bCAzZ4lhMwfMEk+TzmRYBQt245XZtv4nZkmXjDBST6WLp81V0fvvi5/nri1mY5gHdSsvMehzLE1qTcZV0okvEhMUe445DOE9GB6A4ybhDLsbnd0nbcKn70nn7Iwk95YvoJL1IOOd6+8HYFnT0NIZTDWV9/vD2cJwELTLiGktkh6YllUGGF47Iwf6mQfHM2JosM3Kh8OzDdUl6hrZESzsKIjwMgVgPM1qMiYAdRht6CBXGdZrlOK7IYSLZsKvO/JrRYriuS9K4VQkWCBaXziSnn3u4JSccRbMut12BbdakSAf7A92tbtL/WG/xkEzPdzhARkJkIFyuHqScKJlv8DQMy78RqzRAzMUV6C8YaIt5LxwRw8VRTEFRdTQcjD00xMoXy7Uou3T8iNSM74ObTHHxfY2xLr5DRyq5KNQNgT1M0M+NFgGf0ZAWanw+0oTWAq90v2EOGTEMCQwkBxf+fcWvFX222qXHtrT8qjVylZ5rXHim1JQEldvFp8GLYCELy3gbRXuj7xLyr9YYJHsky7KYb0BbJNWj6sDYPlQzsXBqCJ+iPsFzo7uTTM6NKlPtrhsXIflDviQGlEHlAbjE1ONUg3dWmzI22e1CbefGvtBF+c5rc=
env:
  BOTO_CONFIG: /dev/null
