site_name: CFRipper
site_description: "Library and CLI tool for analysing CloudFormation templates and check them for security compliance."
strict: true
site_url: https://cfripper.readthedocs.io

theme:
  name: 'material'
  logo: 'img/logo.png'

repo_name: Skyscanner/cfripper
repo_url: https://github.com/Skyscanner/cfripper

nav:
  - Home: index.md
  - CLI: cli.md
  - Rules: rules.md
  - Rule Config: rule_config.md
  - Changelog: changelog.md
  - Contributing: contributing.md
  - Code of conduct: code_of_conduct.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

plugins:
    - search
    - macros:
        module_name: docs.macros

extra:
  social:
    - type: 'github'
      link: 'https://github.com/Skyscanner'
    - type: 'twitter'
      link: 'https://twitter.com/skyscannereng'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/skyscanner/'