name: PyPI release

on:
  release:
    types: [published]

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/cfripper
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Setup UV
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          python-version: '3.10'
          enable-cache: false

      - name: Build package
        run: make build

      - name: Install dev dependencies
        run: make install-dev

      - name: Check package
        run: make check-package

      - name: Publish distribution 📦 to PyPI
        # zizmor: ignore[use-trusted-publishing] https://github.com/pypi/warehouse/issues/17700
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
        with:
          user: __token__
          password: ${{ secrets.pypi_publish_token }}
