name: Test Docs

on: push

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    name: Test Docs

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup UV
        uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.3.0
        with:
          python-version: '3.10'

      - run: make install-docs

      - run: make test-docs
